# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install smof flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Unit tests
      run: ./runtests.py
    - name: Lint with flake8
      run: flake8 . --statistics --count --show-source --ignore E501,E203,E722,W605,W503
      # This is the most computationally expensive step, so put it last
    - name: Golden tests
      run: |
        pip install .
        sudo apt-get install -y mafft
        ./test.sh
