# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install flake8 mypy
    - name: Lint with flake8
      run: flake8 . --statistics --count --show-source --ignore E501,E203,E722,W605,W503
#    - name: Typechecking
#      run: mypy --python-version 3.10 flutile/*py
    - name: Unit tests
      run: ./runtests.py
      # This is the most computationally expensive step, so put it last
    - name: Golden tests
      run: |
        sudo apt-get install -y mafft
        ./test.sh
